dagen = ("maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag")
print (f"Dit zijn de dagen van de week.{dagen}")
print (f"Dit zijn alle werk dagen in de week.{dagen[0:5]}")
print (f"Dit zijn alle weekend dagen.{dagen[5:6]}")
print (f"Dit zijn de week dagen omgekeerd.{dagen[::-1]}")
print (f"Dit zijn de weekend dagen omgekeerd start zaterdag zondag.{dagen[6:4:-1]}")
print (f"Werk dagen omgekeerd.{dagen[4::-1]}")